apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-template
  labels:
    app.kubernetes.io/name: {{ include "fluentd-elasticsearch.name" . }}
    helm.sh/chart: {{ include "fluentd-elasticsearch.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
data:
  {{ .Values.configuration.template.filename }}: |-
{{ toJson .Values.configuration.template.content | indent 4 }}
